### ISSUE TITLE
Event_h52bag package build fails

### ISSUE THREAD

**Issue by UtharaKeerthan** [tub-rip/events_h52bag#1]
I use a Virtual machine with ubuntu 18.04 and ROS melodic. I followed the procedures mentioned in the read me file. But when I give the make command in the events_h52bag build folder, I get the following error. 
![image](https://user-images.githubusercontent.com/49371846/136953261-1655ffa9-0798-416f-a3bd-722eb081da74.png)
May I know if this issue was seen earlier and if there is a fix for it? Please provide your suggestion,

**Comment by ghoshsuman** [comment]
I have not seen this error before. It seems that HDF5 library is not being found. Make sure that each time after your edit the CMakeLists.txt, remove the build folder, run `cmake..` again inside a new empty build folder and then compile using `make`.

Could you share the output you get after running `cmake ..` in your build folder? Please also share your CMakeLists.txt as well as the installation location of your hdf5 library, which can be found using the `dpkg -L libhdf5-dev` command.

**Comment by UtharaKeerthan** [comment]
Hi, Thanks for the response. 
1. I do the CMake and make after each edit in the CMake. 
Also, I don't get the plugins folder by default in the /usr/lib/x86_64-linux-gnu/hdf5/plugins, so I create one manually and copy the libH5Zblosc.so file. 

2. Please find the following attached text files
    2. a CMakeLists.txt for both blosc and events_tobag folder. I have renamed them for name convenience. 
    [CMakeLists_events_h52bag.txt](https://github.com/tub-rip/events_h52bag/files/7353394/CMakeLists_events_h52bag.txt)
    [CMakeLists_hdf5blosc.txt](https://github.com/tub-rip/events_h52bag/files/7353395/CMakeLists_hdf5blosc.txt)
    2. b The logs of Cmake of both blosc and events_tobag folder.
   [events_h52bag_cmake_log.txt](https://github.com/tub-rip/events_h52bag/files/7353396/events_h52bag_cmake_log.txt)
   [hdf5_blosc_cmake_log.txt](https://github.com/tub-rip/events_h52bag/files/7353397/hdf5_blosc_cmake_log.txt) 
    2. c hdf5 installation location. 
    [hdf5_instl_loc.txt](https://github.com/tub-rip/events_h52bag/files/7353398/hdf5_instl_loc.txt)

**Comment by ghoshsuman** [comment]
I see from the log of your cmake for events_h52bag 
`-- Found HDF5: /usr/local/lib/libhdf5_cpp.so;/usr/local/lib/libhdf5.so;` 
which is not a path at which hdf5 is currently installed in your system. I think the correct path these 2 libraries should be `/usr/lib/...` (without the `local`). When you run cmake, it is probably picking up some residual of an older version of hdf5 you might have in your system which was not properly uninstalled.

I suggest removing those stray library files from your system so that the cmake picks up the correct paths:
`/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so` and `/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_cpp.so`

**Comment by UtharaKeerthan** [comment]
Thanks a lot for the response. I still had some issues with my CMake settings. I tried from scratch in a new virtual env(ubuntu 20) and it worked.

**Comment by robin-shaun** [comment]
Hi, I met the same problem. Different from UtharaKeerthan, my CMake log shows that `-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_cpp.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.0.1") found components:  CXX`. I think it find HDF5, but when I make, problem `/home/robin/event_based_vision/events_h52bag/src/main.cpp:25:14: error: ‘class H5::H5File’ has no member named ‘exists’
     if(!file.exists(dataset.c_str())){
` happens.

**Comment by ghoshsuman** [comment]
@robin-shaun Please share the installation location of your hdf5 library, which can be found using the dpkg -L libhdf5-dev command

**Comment by ghoshsuman** [comment]
@robin-shaun Please share the installation location of your hdf5 library, which can be found using the dpkg -L libhdf5-dev command

**Comment by robin-shaun** [comment]
@ghoshsuman 
![image](https://user-images.githubusercontent.com/20561850/140717387-2f25ac8d-5405-4e46-a97a-db400aa9d75a.png)

**Comment by ghoshsuman** [comment]
Can you check which version of hdf5 you have installed using `dpkg -l | grep hdf5` ?

**Comment by robin-shaun** [comment]
![image](https://user-images.githubusercontent.com/20561850/140724168-a36edd0e-6e6a-473d-bda0-cdc7791a37b4.png)

**Comment by ghoshsuman** [comment]
Could you try upgrading to hdf5 version 1.10.4 on your system?

**Comment by robin-shaun** [comment]
![image](https://user-images.githubusercontent.com/20561850/140728328-b18ea003-a79e-403a-b511-48e3ea62fa0d.png)
Maybe Ubuntu18.04 doesn't support 1.10.4

**Comment by ghoshsuman** [comment]
I have modified the code to use H5Lexists() which should exist in libhdf5 1.10.0. Could you pull the latest version of this repo and try again on your system?

**Comment by robin-shaun** [comment]
It works, thanks a lot.
