### ISSUE TITLE
Output frequency 

### ISSUE THREAD

**Issue by robin-shaun** [tub-rip/events_h52bag#4]
Hello, I convert the h5file from https://vision.in.tum.de/data/datasets/visual-inertial-event-dataset to rosbag. The rostopic output frequency is higher than 175 Hz, not the same as the rpg_dv_ros (30Hz). How to adjust the output frequency?

**Comment by ghoshsuman** [comment]
You could try increasing the packet size [here](https://github.com/tub-rip/events_h52bag/blob/2f24d3d96746619aa6a8e305c10a89e11d05217c/src/main.cpp#L106) to decrease the frequency of event packets.

**Comment by robin-shaun** [comment]
Ok ,thanks a lot.
