### ISSUE TITLE
Error while excuting events_h52bag

### ISSUE THREAD

**Issue by dhm126** [tub-rip/events_h52bag#5]
hi ghosh,while excuting `./events_h52bag` ,I've encountered such problem as follow:
<img width="337" alt="1" src="https://user-images.githubusercontent.com/74313353/173001103-67ff504d-a822-412a-a0cf-c760a9590faa.png">

I did the same procedure as instructions in Readme.md and put the `libH5Zblosc.so` in the plugin directory.I wonder how to handle this issue.
thanks for your reply

**Comment by ghoshsuman** [comment]
Sorry for the late response. Did you manage to solve this issue? 
If not, can you tell me what is the path of the plugin folder in which you are pasting the `libH5Zblosc.so` file?

If this system-wide installation of the blosc filter fails for you, you could also alternatively registering blosc specifically for your C++ application: https://github.com/Blosc/hdf5-blosc#linking-the-blosc-filter-directly-into-your-program

**Comment by dhm126** [comment]
Hi,ghosh.Thanks for your reply! I seemed to solve this problem but I forgot details.
