### ISSUE TITLE
Error in H5Fopen()

### ISSUE THREAD

**Issue by aelmoudni** [tub-rip/events_h52bag#6]
Hi, 

I have been trying to use your code to convert .h5 files to rosbags, but i keep having the same error while trying to execute a conversion, this ks the error: 
"""
Reading dataset events/t
rank 1, dimensions 643970457
ndims :1
count: 643970457 0
Vectsize: 643970457
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 139954026966272:
  #000: ../../../src/H5Dio.c line 199 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: ../../../src/H5Dio.c line 601 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: ../../../src/H5Dchunk.c line 2229 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: ../../../src/H5Dchunk.c line 3609 in H5D__chunk_lock(): data pipeline read failed
    major: Dataset
    minor: Filter operation failed
  #004: ../../../src/H5Z.c line 1301 in H5Z_pipeline(): required filter 'blosc' is not registered
    major: Data filters
    minor: Read failed
"""

Any ideas how i can resolve this ?

**Comment by ghoshsuman** [comment]
Hi @aelmoudni , looking at the error message it seems that the blosc filter used for data (de-)compression was not found in your system. Which version of Ubuntu and libhdf5 are you using?  Did you install the blosc filter plugin and copy the generated `libH5Zblosc.so` library file in your system's hdf5 `plugins` directory? In Ubuntu 20.04, the plugins path is usually `/usr/lib/x86_64-linux-gnu/hdf5/plugins`. If this path does not exist for you, can you run `dpkg -L libhdf5-dev` on your terminal and post your output here?

**Comment by ghoshsuman** [comment]
Hi @aelmoudni are you still facing issues?
