### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by grabowskimariusz94** [tub-rip/events_h52bag#7]
Hi,
I followed the instructions in the README, but I came across a problem when executing the program.

![image](https://user-images.githubusercontent.com/71455615/232335424-78ef70de-8d5e-41d2-b9a8-3bd160fad030.png)

I use a virtual machine with Ubuntu 20.04.

Regards

**Comment by ghoshsuman** [comment]
Could you please share details about the data that you are using, as well as the libhdf5 version you are using?

**Comment by grabowskimariusz94** [comment]
Hi, Thanks for the response.
I managed to solve the problem by re-installing libhdf5 through python-pip.

Regards
